default:
  DUPLO_CHECK: True
  DIR_MODEL_WORDS: model_words\por_words.txt
  MODEL_NAME: swsl_resnext50_32x4d
  ALBUMENTATIONS_HEIGHT: 224
  ALBUMENTATIONS_WIDHT: 224
  ALBUMENTATIONS_NORMALIZE: 1

production: